### ISSUE TITLE
HTML is not loading

### ISSUE THREAD

**Issue by adityachandavale** [Faouzizi/flaskCreateContactForms#1]
Giving "Not found requested URL not found on server error'.
Terminal giving "GET / HTTP/1.1" 404
Project is not starting. Also, project is only cloned, and no changes were made. All specified requirements are already installed on my system.
![image](https://user-images.githubusercontent.com/67214878/129845975-e0f9502e-c47c-4d28-904d-0752f6852f5b.png)
![image](https://user-images.githubusercontent.com/67214878/129846032-38aa408e-fef8-4c67-ac0b-0c1258049bd3.png)

**Comment by Faouzizi** [comment]
Hi @adityachandavale, 

Thank you for your comment. 
Actually, the html page is located there : http://127.0.0.1:5000/contactus
So can you try to navigate to this page and check if it's work well ? 

I will add some more informations in the readme.
Thank you again :)

**Comment by adityachandavale** [comment]
It worked now, thank you!
